In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, log_loss
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.isna().sum()

id           0
species      0
margin1      0
margin2      0
margin3      0
margin4      0
margin5      0
margin6      0
margin7      0
margin8      0
margin9      0
margin10     0
margin11     0
margin12     0
margin13     0
margin14     0
margin15     0
margin16     0
margin17     0
margin18     0
margin19     0
margin20     0
margin21     0
margin22     0
margin23     0
margin24     0
margin25     0
margin26     0
margin27     0
margin28     0
            ..
texture35    0
texture36    0
texture37    0
texture38    0
texture39    0
texture40    0
texture41    0
texture42    0
texture43    0
texture44    0
texture45    0
texture46    0
texture47    0
texture48    0
texture49    0
texture50    0
texture51    0
texture52    0
texture53    0
texture54    0
texture55    0
texture56    0
texture57    0
texture58    0
texture59    0
texture60    0
texture61    0
texture62    0
texture63    0
texture64    0
Length: 194, dtype: int64

In [4]:
df.describe()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
count,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,...,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000
mean,799.595960,0.017412,0.028539,0.031988,0.023280,0.014264,0.038579,0.019202,0.001083,0.007167,...,0.036501,0.005024,0.015944,0.011586,0.016108,0.014017,0.002688,0.020291,0.008989,0.019420
std,452.477568,0.019739,0.038855,0.025847,0.028411,0.018390,0.052030,0.017511,0.002743,0.008933,...,0.063403,0.019321,0.023214,0.025040,0.015335,0.060151,0.011415,0.039040,0.013791,0.022768
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,415.250000,0.001953,0.001953,0.013672,0.005859,0.001953,0.000000,0.005859,0.000000,0.001953,...,0.000000,0.000000,0.000977,0.000000,0.004883,0.000000,0.000000,0.000000,0.000000,0.000977
50%,802.500000,0.009766,0.011719,0.025391,0.013672,0.007812,0.015625,0.015625,0.000000,0.005859,...,0.004883,0.000000,0.005859,0.000977,0.012695,0.000000,0.000000,0.003906,0.002930,0.011719
75%,1195.500000,0.025391,0.041016,0.044922,0.029297,0.017578,0.056153,0.029297,0.000000,0.007812,...,0.043701,0.000000,0.022217,0.009766,0.021484,0.000000,0.000000,0.023438,0.012695,0.029297
max,1584.000000,0.087891,0.205080,0.156250,0.169920,0.111330,0.310550,0.091797,0.031250,0.076172,...,0.429690,0.202150,0.172850,0.200200,0.106450,0.578130,0.151370,0.375980,0.086914,0.141600

In [5]:
df.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

#### function for Label Encoding

In [6]:
def LabelEncoding():
    l = LabelEncoder()
    df['labeled_species']=l.fit_transform(df['species'])
    df.drop('species', axis=1, inplace=True)

In [7]:
LabelEncoding()

In [8]:
df.drop('id', axis=1, inplace=True)

In [9]:
df.head()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64,labeled_species
0,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,0.001953,0.033203,...,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391,3
1,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,0.000000,0.007812,...,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461,49
2,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,0.000000,0.044922,...,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930,65
3,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,0.013672,0.017578,...,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852,94
4,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,0.000000,0.005859,...,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250,84

In [10]:
list(df.columns)

['margin1',
 'margin2',
 'margin3',
 'margin4',
 'margin5',
 'margin6',
 'margin7',
 'margin8',
 'margin9',
 'margin10',
 'margin11',
 'margin12',
 'margin13',
 'margin14',
 'margin15',
 'margin16',
 'margin17',
 'margin18',
 'margin19',
 'margin20',
 'margin21',
 'margin22',
 'margin23',
 'margin24',
 'margin25',
 'margin26',
 'margin27',
 'margin28',
 'margin29',
 'margin30',
 'margin31',
 'margin32',
 'margin33',
 'margin34',
 'margin35',
 'margin36',
 'margin37',
 'margin38',
 'margin39',
 'margin40',
 'margin41',
 'margin42',
 'margin43',
 'margin44',
 'margin45',
 'margin46',
 'margin47',
 'margin48',
 'margin49',
 'margin50',
 'margin51',
 'margin52',
 'margin53',
 'margin54',
 'margin55',
 'margin56',
 'margin57',
 'margin58',
 'margin59',
 'margin60',
 'margin61',
 'margin62',
 'margin63',
 'margin64',
 'shape1',
 'shape2',
 'shape3',
 'shape4',
 'shape5',
 'shape6',
 'shape7',
 'shape8',
 'shape9',
 'shape10',
 'shape11',
 'shape12',
 'shape13',
 'shape14',
 'shape15',
 'shape16',
 'shape17',
 'shape18',
 'shape19',
 'shape20',
 'shape21',
 'shape22',
 'shape23',
 'shape24',
 'shape25',
 'shape26',
 'shape27',
 'shape28',
 'shape29',
 'shape30',
 'shape31',
 'shape32',
 'shape33',
 'shape34',
 'shape35',
 'shape36',
 'shape37',
 'shape38',
 'shape39',
 'shape40',
 'shape41',
 'shape42',
 'shape43',
 'shape44',
 'shape45',
 'shape46',
 'shape47',
 'shape48',
 'shape49',
 'shape50',
 'shape51',
 'shape52',
 'shape53',
 'shape54',
 'shape55',
 'shape56',
 'shape57',
 'shape58',
 'shape59',
 'shape60',
 'shape61',
 'shape62',
 'shape63',
 'shape64',
 'texture1',
 'texture2',
 'texture3',
 'texture4',
 'texture5',
 'texture6',
 'texture7',
 'texture8',
 'texture9',
 'texture10',
 'texture11',
 'texture12',
 'texture13',
 'texture14',
 'texture15',
 'texture16',
 'texture17',
 'texture18',
 'texture19',
 'texture20',
 'texture21',
 'texture22',
 'texture23',
 'texture24',
 'texture25',
 'texture26',
 'texture27',
 'texture28',
 'texture29',
 'texture30',
 'texture31',
 'texture32',
 'texture33',
 'texture34',
 'texture35',
 'texture36',
 'texture37',
 'texture38',
 'texture39',
 'texture40',
 'texture41',
 'texture42',
 'texture43',
 'texture44',
 'texture45',
 'texture46',
 'texture47',
 'texture48',
 'texture49',
 'texture50',
 'texture51',
 'texture52',
 'texture53',
 'texture54',
 'texture55',
 'texture56',
 'texture57',
 'texture58',
 'texture59',
 'texture60',
 'texture61',
 'texture62',
 'texture63',
 'texture64',
 'labeled_species']

# LDA

In [13]:
features = ['margin1','margin2','margin3','margin4','margin5','margin6','margin7','margin8','margin9','margin10','margin11','margin12','margin13','margin14','margin15','margin16','margin17','margin18','margin19','margin20',
'margin21','margin22','margin23','margin24','margin25','margin26','margin27','margin28','margin29','margin30','margin31',
'margin32','margin33','margin34','margin35','margin36','margin37','margin38','margin39','margin40','margin41','margin42',
'margin43','margin44','margin45','margin46','margin47','margin48','margin49','margin50','margin51','margin52','margin53',
'margin54','margin55','margin56','margin57','margin58','margin59','margin60','margin61','margin62','margin63','margin64',
'shape1','shape2','shape3','shape4','shape5','shape6','shape7','shape8','shape9','shape10','shape11','shape12','shape13',
'shape14','shape15','shape16','shape17','shape18','shape19','shape20','shape21','shape22','shape23','shape24','shape25',
'shape26','shape27','shape28','shape29','shape30','shape31','shape32','shape33','shape34','shape35','shape36','shape37',
'shape38','shape39','shape40','shape41','shape42','shape43','shape44','shape45','shape46','shape47','shape48','shape49',
'shape50','shape51','shape52','shape53','shape54','shape55','shape56','shape57','shape58','shape59','shape60','shape61',
'shape62','shape63','shape64','texture1','texture2','texture3','texture4','texture5','texture6','texture7','texture8',
'texture9','texture10','texture11','texture12','texture13','texture14','texture15','texture16','texture17','texture18',
'texture19','texture20','texture21','texture22','texture23','texture24','texture25','texture26','texture27','texture28',
'texture29','texture30','texture31','texture32','texture33','texture34','texture35','texture36','texture37','texture38',
'texture39','texture40','texture41','texture42','texture43','texture44','texture45','texture46','texture47','texture48',
'texture49','texture50','texture51','texture52','texture53','texture54','texture55','texture56','texture57','texture58',
'texture59','texture60','texture61','texture62','texture63','texture64']
label = ['labeled_species']
X=df[features]
Y=df[label]

In [14]:
Z=df.iloc[:,0:192]  #alternate

In [12]:
lda = LinearDiscriminantAnalysis(n_components=192)
lda.fit(X,Y)

C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(192, 99 - 1) = 98 components.
  ChangedBehaviorWarning)
C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")

LinearDiscriminantAnalysis(n_components=192, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [13]:
np.cumsum(lda.explained_variance_ratio_)

array([0.15025048, 0.22550711, 0.29486482, 0.35201967, 0.3986852 ,
       0.43965218, 0.47659408, 0.51094167, 0.53810846, 0.56466542,
       0.5893243 , 0.61217345, 0.63458117, 0.65557411, 0.67376658,
       0.69102335, 0.70675838, 0.72179435, 0.73591993, 0.74873703,
       0.76116956, 0.77336177, 0.78481287, 0.7955628 , 0.80588575,
       0.81574793, 0.82515573, 0.8340712 , 0.8424567 , 0.85055492,
       0.85838678, 0.86566283, 0.87277344, 0.87925774, 0.88558279,
       0.89144445, 0.89713124, 0.90266207, 0.90792888, 0.91281508,
       0.91734725, 0.92164517, 0.9258108 , 0.92975358, 0.93341738,
       0.93697985, 0.94042474, 0.94373714, 0.94693018, 0.94995334,
       0.95283228, 0.9554355 , 0.95787834, 0.96026582, 0.96259241,
       0.96480681, 0.96688272, 0.96883643, 0.97074635, 0.97256566,
       0.97424588, 0.97580046, 0.97731275, 0.97870399, 0.98003882,
       0.98135108, 0.98255591, 0.98374061, 0.98485316, 0.98593265,
       0.98697362, 0.98798094, 0.98891687, 0.98975841, 0.99058522,
       0.99137719, 0.99213468, 0.99284849, 0.99348422, 0.99408926,
       0.99466252, 0.9952164 , 0.99573281, 0.99622123, 0.9966921 ,
       0.99709923, 0.99748278, 0.99782602, 0.99811776, 0.99840185,
       0.99867759, 0.99894797, 0.99917268, 0.99938951, 0.99958306,
       0.99974615, 0.99988116, 1.        ])

#### first 98 LDA components are explaining the 100% variance in Data

In [14]:
newdf = lda.transform(X)
df_LDA = pd.DataFrame(newdf)

In [15]:
df_LDA.head()

,0,1,2,3,4,5,6,7,8,9,...,88,89,90,91,92,93,94,95,96,97
0,-0.648797,0.537300,-0.809578,4.272160,0.084238,-2.145883,-1.894886,-0.711627,-0.671764,1.863463,...,1.506146,1.795634,-0.084553,-1.296280,-0.396366,0.009959,0.681139,1.153277,-0.585805,0.526974
1,-8.804349,-0.258461,-3.006685,0.709335,-4.388313,-3.041601,1.268355,0.292732,2.028151,0.223082,...,0.481770,0.880941,0.456243,0.304505,1.094466,1.471566,0.798527,-1.001072,0.401249,-0.089090
2,-1.790432,4.762001,2.500650,8.649696,1.592850,-1.532324,-4.586159,3.251663,-2.526334,-3.039781,...,0.087102,-0.723874,0.845684,0.525387,1.135175,0.571597,-0.073347,-1.161657,-0.344413,-1.433593
3,-7.613506,-2.244059,-1.697840,1.680766,1.371611,-0.637791,3.070569,-1.525727,-1.115488,4.544844,...,-2.874230,0.520055,-0.335213,1.104496,3.086382,-0.363377,0.413000,1.702472,0.202693,0.230396
4,2.363719,0.865242,5.755119,2.533807,-2.546901,0.961686,5.417776,-5.203861,0.246966,9.641446,...,0.697603,-0.092371,0.578127,1.313332,1.226233,2.055036,-0.136389,1.299468,-1.094203,-0.097703

# Train Test Splitting

In [27]:
seed = 177
features = [0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
label = ['labeled_species']
X=df_LDA[features]
Y=df[label]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=.20,random_state=seed)

# Classifiers Class

In [28]:
class Classifiers:
    
    def CreateDTModel(X_train,Y_train):
        dt = DecisionTreeClassifier(max_depth=5, random_state=seed)
        model=dt.fit(X_train, Y_train)
        return model

    def CreateRFModel(X_train,Y_train):
        rf = RandomForestClassifier(n_estimators=250, max_depth=5, random_state=seed)
        model=rf.fit(X_train, Y_train)
        return model

    def CreateNBModel(X_train, Y_train):
        nb=GaussianNB()
        model=nb.fit(X_train, Y_train)
        return model

    def CreateSVCModel(X_train, Y_train):
        svc=SVC(random_state=seed)
        model=svc.fit(X_train, Y_train)
        return model
    
    def GetPrediction(model,X_test):
        pred=model.predict(X_test)
        return pred
    
    def GetAccuracy(Y_test, pred):
        accscore = accuracy_score(Y_test, pred)
        return accscore
    
    def Overfitting(model,X_train):
        pred=model.predict(X_train)
        return pred
    
    def OverfitAccuracy(Y_train, pred):
        accscore = accuracy_score(Y_train, pred)
        return accscore

In [66]:
# Decision Tree
model=Classifiers.CreateDTModel(X_train, Y_train)
pred=Classifiers.GetPrediction(model, X_test)
accscore = Classifiers.GetAccuracy(Y_test, pred)
print("Decision Tree Accuracy Score = ",accscore)

all_classes = list(set(Y['labeled_species']))
pred=model.predict_proba(X_test)
print("Decision Tree Logg_Loss score = ", log_loss(Y_test, pred, labels=all_classes))

pred=Classifiers.Overfitting(model, X_train)
accscore = Classifiers.OverfitAccuracy(Y_train, pred)
print("Decision Tree OverFit Score = ",accscore)

Decision Tree Accuracy Score =  0.03535353535353535
Decision Tree Logg_Loss score =  4.251180814174287
Decision Tree OverFit Score =  0.0946969696969697

In [63]:
# Random Forest
model=Classifiers.CreateRFModel(X_train, Y_train)
pred=Classifiers.GetPrediction(model, X_test)
accscore = Classifiers.GetAccuracy(Y_test, pred)
print("Random Forest Accuracy Score = ",accscore)

all_classes = list(set(Y['labeled_species']))
pred=model.predict_proba(X_test)
print("Random Forest Logg_Loss score = ", log_loss(Y_test, pred, labels=all_classes))

pred=Classifiers.Overfitting(model, X_train)
accscore = Classifiers.OverfitAccuracy(Y_train, pred)
print("Random Forest OverFit Score = ",accscore)

C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.

Random Forest Accuracy Score =  0.7777777777777778
Random Forest Logg_Loss score =  3.1154055396748483
Random Forest OverFit Score =  0.9621212121212122

In [59]:
# Naive Bayes
model=Classifiers.CreateNBModel(X_train, Y_train)
pred=Classifiers.GetPrediction(model, X_test)
accscore = Classifiers.GetAccuracy(Y_test, pred)
print("Naive Bayes Accuracy Score = ",accscore)

all_classes = list(set(Y['labeled_species']))
pred=model.predict_proba(X_test)
print("Naive Bayes Logg Loss score = ", log_loss(Y_test, pred, labels=all_classes))

pred=Classifiers.Overfitting(model, X_train)
accscore = Classifiers.OverfitAccuracy(Y_train, pred)
print("Naive bayes OverFit Score = ",accscore)

Naive Bayes Accuracy Score =  0.98989898989899
Naive Bayes Logg Loss score =  0.22196355441395565
Naive bayes OverFit Score =  1.0

C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [67]:
# Support Vector
model=Classifiers.CreateSVCModel(X_train, Y_train)
pred=Classifiers.GetPrediction(model, X_test)
accscore = Classifiers.GetAccuracy(Y_test, pred)
print("Support Vector Accuracy Score = ",accscore)

pred=Classifiers.Overfitting(model, X_train)
accscore = Classifiers.OverfitAccuracy(Y_train, pred)
print("Support Vector OverFit Score = ",accscore)

C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Support Vector Accuracy Score =  0.9797979797979798
Support Vector OverFit Score =  1.0

# Both NaiveBayes and SVC classifiers has the best Accuracy score as per above analysis

# Now Predicting Results on Test.csv dataset

In [80]:
df_test = pd.read_csv('test.csv')

In [81]:
df_test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [82]:
features = ['margin1','margin2','margin3','margin4','margin5','margin6','margin7','margin8','margin9','margin10','margin11','margin12','margin13','margin14','margin15','margin16','margin17','margin18','margin19','margin20',
'margin21','margin22','margin23','margin24','margin25','margin26','margin27','margin28','margin29','margin30','margin31',
'margin32','margin33','margin34','margin35','margin36','margin37','margin38','margin39','margin40','margin41','margin42',
'margin43','margin44','margin45','margin46','margin47','margin48','margin49','margin50','margin51','margin52','margin53',
'margin54','margin55','margin56','margin57','margin58','margin59','margin60','margin61','margin62','margin63','margin64',
'shape1','shape2','shape3','shape4','shape5','shape6','shape7','shape8','shape9','shape10','shape11','shape12','shape13',
'shape14','shape15','shape16','shape17','shape18','shape19','shape20','shape21','shape22','shape23','shape24','shape25',
'shape26','shape27','shape28','shape29','shape30','shape31','shape32','shape33','shape34','shape35','shape36','shape37',
'shape38','shape39','shape40','shape41','shape42','shape43','shape44','shape45','shape46','shape47','shape48','shape49',
'shape50','shape51','shape52','shape53','shape54','shape55','shape56','shape57','shape58','shape59','shape60','shape61',
'shape62','shape63','shape64','texture1','texture2','texture3','texture4','texture5','texture6','texture7','texture8',
'texture9','texture10','texture11','texture12','texture13','texture14','texture15','texture16','texture17','texture18',
'texture19','texture20','texture21','texture22','texture23','texture24','texture25','texture26','texture27','texture28',
'texture29','texture30','texture31','texture32','texture33','texture34','texture35','texture36','texture37','texture38',
'texture39','texture40','texture41','texture42','texture43','texture44','texture45','texture46','texture47','texture48',
'texture49','texture50','texture51','texture52','texture53','texture54','texture55','texture56','texture57','texture58',
'texture59','texture60','texture61','texture62','texture63','texture64']

X2=df_test[features]

In [84]:
# Naive Bayes
nb=GaussianNB()
model=nb.fit(X, Y)
pred=model.predict(X2)
pred

C:\Users\bpeddi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: operands could not be broadcast together with shapes (594,192) (98,)

In [ ]:
# Support Vector
model=Classifiers.CreateSVCModel(X_train, Y_train)
pred=Classifiers.GetPrediction(model, X_test)